version: '3'

networks:
  etcd_network:

services:
  etcd-1:
    image: quay.io/coreos/etcd:v3.1.20
    entrypoint: /usr/local/bin/etcd
    command:
      - '--name=etcd-1'
      - '--initial-advertise-peer-urls=http://etcd-1:2380'
      - '--listen-peer-urls=http://etcd-1:2380'
      - '--listen-client-urls=http://etcd-1:2379,http://localhost:2379'
      - '--advertise-client-urls=http://etcd-1:2379'
      - '--initial-cluster-token=mytoken'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
      - '--initial-cluster-state=new'
    ports:
      - 9001:2379
    networks:
      etcd_network:
    volumes:
      - etcd1:/etcd_data
  etcd-2:
    image: quay.io/coreos/etcd:v3.1.20
    entrypoint: /usr/local/bin/etcd
    command:
      - '--name=etcd-2'
      - '--initial-advertise-peer-urls=http://etcd-2:2380'
      - '--listen-peer-urls=http://etcd-2:2380'
      - '--listen-client-urls=http://etcd-2:2379,http://localhost:2379'
      - '--advertise-client-urls=http://etcd-2:2379'
      - '--initial-cluster-token=mytoken'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
      - '--initial-cluster-state=new'
    ports:
      - 9002:2379
    networks:
      etcd_network:
    volumes:
      - etcd2:/etcd_data
  etcd-3:
    image: quay.io/coreos/etcd:v3.1.20
    entrypoint: /usr/local/bin/etcd
    command:
      - '--name=etcd-3'
      - '--initial-advertise-peer-urls=http://etcd-3:2380'
      - '--listen-peer-urls=http://etcd-3:2380'
      - '--listen-client-urls=http://etcd-3:2379,http://localhost:2379'
      - '--advertise-client-urls=http://etcd-3:2379'
      - '--initial-cluster-token=mytoken'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
      - '--initial-cluster-state=new'
    ports:
      - 9003:2379
    networks:
      etcd_network:
    volumes:
      - etcd3:/etcd_data
volumes:
  etcd1:
  etcd2:
  etcd3:
