version: '3'

networks:
  etcd_network:

services:
  etcd1:
    image: quay.io/coreos/etcd:v3.4.4
    entrypoint: /usr/local/bin/etcd
    command: >
      --name etcd1
      --initial-advertise-peer-urls http://${HOST}:2380
      --listen-peer-urls http://0.0.0.0:2380
      --advertise-client-urls http://${HOST}:2379
      --listen-client-urls http://0.0.0.0:2379
      --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      --log-level=debug
    expose:
      - 2379
      - 2380
    ports:
      - 9001:2379
      - 3381:2380
    networks:
      etcd_network:
  etcd2:
    image: quay.io/coreos/etcd:v3.4.4
    entrypoint: /usr/local/bin/etcd
    command: >
      --name etcd2
      --initial-advertise-peer-urls http://${HOST}:2380
      --listen-peer-urls http://0.0.0.0:2380
      --advertise-client-urls http://${HOST}:2379
      --listen-client-urls http://0.0.0.0:2379
      --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      --log-level=debug
    expose:
      - 2379
      - 2380
    ports:
      - 9002:2379
      - 3382:2380
    networks:
      etcd_network:
  etcd3:
    image: quay.io/coreos/etcd:v3.4.4
    entrypoint: /usr/local/bin/etcd
    command: >
      --name etcd3
      --initial-advertise-peer-urls http://${HOST}:2380
      --listen-peer-urls http://0.0.0.0:2380
      --advertise-client-urls http://${HOST}:2379
      --listen-client-urls http://0.0.0.0:2379
      --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      --log-level=debug
    expose:
      - 2379
      - 2380
    ports:
      - 9003:2379
      - 3383:2380
    networks:
      etcd_network:

